name: Build PsychExtended + Release
run-name: PsychExtended v1.0.2 Beta 2
on: workflow_dispatch

permissions:
  contents: write
  discussions: write

env:
  PROJECT_NAME: PsychEngine
  REPO_PATH: https://github.com/PsychExtendedThings/Psych-Extended-ReBase

jobs:
  build:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Android
            os: ubuntu-24.04
            buildArgs: "android -D officialBuild -final" 
            setupCommand: sh ./setup/unix.sh
            artifactName: androidBuild
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
            system: Android
          - name: Windows
            os: windows-2022
            buildArgs: "windows -D officialBuild -final"
            setupCommand: .\"setup/windows.bat"
            artifactName: windowsBuild-x86_64
            artifactPath: export\release\windows\bin\*
            system: Windows
    uses: ./.github/workflows/build.yml
    with:
        name: ${{ matrix.name }}
        os: ${{ matrix.os }}
        setupCommand: ${{ matrix.setupCommand }}
        buildArgs: ${{ matrix.buildArgs }}
        artifactName: ${{ matrix.artifactName }}
        artifactPath: ${{ matrix.artifactPath }}
        system: ${{ matrix.system }}

  Releaser:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download Android Build
        uses: actions/download-artifact@main
        with:
           name: androidBuild
           path: /home/runner

      - name: Move Android File
        run: mv /home/runner/${{ env.PROJECT_NAME }}-release.apk /home/runner/PsychExtended-v102-Beta2-Update.apk

      - name: Publish The Release
        uses: softprops/action-gh-release@v2
        with:
          name: "DevBuild"
          tag_name: "1.0.2-beta2"
          prerelease: true
          files: |
            /home/runner/*.apk
            /home/runner/*.zip
            /home/runner/*.tar